apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
  name: postgres-ql
  namespace: argocd
spec:
  destination:
    namespace: postgres-ql
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |
        global:
          imageRegistry: ""
          imagePullSecrets: []
          storageClass: ""
          postgresql:
            auth:
              postgresPassword: ""
              username: "cbadmin"
              password: "cbadmin"
              database: ""
              existingSecret: ""
              secretKeys:
                adminPasswordKey: ""
                userPasswordKey: ""
                replicationPasswordKey: ""
            service:
              ports:
                postgresql: ""
    path: bitnami/postgresql
    repoURL: https://github.com/bitnami/charts
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true