apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: ./
    repoURL: https://github.com/corentin-guenot/my-postgresql.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 